In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iriscsv/Iris.csv


In [2]:
import pandas as pd
import numpy as np
import plotly
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.offline as pyo
import cufflinks as cf  
from plotly.offline import init_notebook_mode, plot, iplot
from pandas.plotting import scatter_matrix

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input/iriscsv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/iriscsv/Iris.csv


In [4]:
df= pd.read_csv("/kaggle/input/iriscsv/Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df1=df.drop('Id', axis=1)
df1.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df1.shape

(150, 5)

**Visualization Data**

In [7]:
px.scatter(df1, x='Species', y='PetalWidthCm')

In [8]:
px.line(df1, x='Species', y='PetalWidthCm')

In [9]:
df2 = df1.rename(columns={'SepalLengthCm':'SepalLength','SepalWidthCm':'SepalWidth',
                           'PetalLengthCm':'PetalLength','PetalWidthCm':'PetalWidth'})
df2.head()

SepalLength  SepalWidth  PetalLength  PetalWidth      Species
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

**Correlation Visualization**

In [10]:
px.scatter_matrix(df2, color='Species', title='Iris', dimensions=['SepalLength','SepalWidth',
                                                                  'PetalLength','PetalWidth'])

**Features Engineering**

In [11]:
x= df2.drop('Species', axis=1)
y = df2['Species'].copy()

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**TRIAN SET & TEST SET**

USING DECISION TREE

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)
x_train.shape

(120, 4)

In [14]:
y_train.size

120

**Decision Tree Classifier Model**

In [15]:
from sklearn import tree

dt_model = tree.DecisionTreeClassifier()
dt_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [16]:
from sklearn.metrics import accuracy_score

prediction_dt = dt_model.predict(x_test)
accuracy_dt = accuracy_score(y_test, prediction_dt)*100

In [17]:
accuracy_dt

100.0

**CROSS VALIDATION**

In [18]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(dt_model,x_train, y_train, scoring='neg_mean_squared_error', cv=20)
rmse_scores = np.sqrt(-scores)
rmse_scores

array([0.        , 0.40824829, 0.40824829, 0.40824829, 0.40824829,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.40824829, 0.40824829, 0.        ,
       0.40824829, 0.40824829, 0.        , 0.40824829, 0.        ])

In [19]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [20]:
prediction_dt

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

**Creating Catagory**

In [21]:
catagory = ['Iris-Satosa','Iris-Versicolor','Iris-Virginica']

**Test a random data using DecisionTreeClassifier Model**

In [22]:
data = 1,3,2,1.1

In [23]:
data_array = np.array([data])
data_array

array([[1. , 3. , 2. , 1.1]])

In [24]:
predic = dt_model.predict(data_array)
print(catagory[int(predic[0])])

Iris-Versicolor


/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names

